### ISSUE TITLE
The receipt is not sent immediately

### ISSUE THREAD

**Issue by jacob-y** [link-it/govpay#355]
Hello,

Sorry I am a french developer that works on a SaaS product for the europe market, so I do not speak italian. 
I will communicate in english instead.

**Descrizione del Bug**

When I trigger a payment with gpCaricaVersamento, the RT fields are not always sent immediately after the payment (I get it with gpChiediStatoVersamento).

The normal behavior is to send a fiscal immediately

It depends on the payment method the donor used, sometimes it works, sometimes not.

For instance we paypal, we get these:

- rpt_datiVersamento_identificativoUnivocoVersamento
- datiVersamento_datiSingoloVersamento_0_causaleVersamento

But not these:

- istitutoAttestante_identificativoUnivocoAttestante_codiceIdentificativoUnivoco
- istitutoAttestante_denominazioneAttestante
- datiPagamento_datiSingoloPagamento_0_identificativoUnivocoRiscossione

Do you know if there is a problem on GovPay here ?

Or if we have a problem with our configuration / customer accounts ?

Thanks,
Yann

**Comment by nardil** [comment]
Hi Jacob,

the operations 'gpCaricaVersamento' or 'gpChiediStatoVersamento' were exposed by GovPay until version 2.6 and replaced by by REST API since version 3.0. Community version 2.x is no longer supported. 

Anyway, GovPay sends two notification:
- one at the beginning of payment transaction, when the payment request (RPT) is accepted by pagoPA, and it will not contains the RT field.
- one at the end of payment transaction, when pagoPA sends the receipt (RT), and it will contains the RT field. 

the PSP and the payment method could affect the delay between the payment execution and the emission of the receipt.
